# Clean scraped data

In [1]:
import pandas as pd

In [2]:
# pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_rows')

In [3]:
df = pd.read_csv('products.csv')

In [4]:
df.shape

(1467, 8)

# Remove Duplicates
* some pages show 48 found products instead of 24
* after looking into products with the same `href`, most of them are only different in price (one row has a price, one does not)
* since we want to remove all rows without a price anyway (because most of the time this means that the product is not available anyway), we just do that and this should remove most of the duplicates

Pages with 48 products (output of other notebook):
* Scraping page 24, 48 products found
* Scraping page 25, 48 products found
* Scraping page 26, 48 products found
* Scraping page 27, 48 products found
* Scraping page 28, 48 products found
* Scraping page 29, 48 products found
* Scraping page 30, 48 products found
* Scraping page 31, 48 products found

In [5]:
href_duplikate_df = df[df.duplicated(subset=["href"], keep=False)].sort_values("href").reset_index(drop=True)

href_duplikate_df

,href,name,brand,price,product_details,instruction,ingredients,warnings
0,https://www.rossmann.de/de/gesundheit-altaphar...,Lippen-Herpes-Gel,altapharma,"Artikelpreis 3,99 €",Das altapharma Lippen-Herpes-Gel ist ideal für...,altapharma Lippen-Herpes-Gel bis zu 5-mal tägl...,"Aqua purificata, Octyldodecanol, Hydrogenated ...",Warnhinweise\nNur zur äußerlichen Anwendung be...
1,https://www.rossmann.de/de/gesundheit-altaphar...,Lippen-Herpes-Gel,altapharma,NaN,Das altapharma Lippen-Herpes-Gel ist ideal für...,altapharma Lippen-Herpes-Gel bis zu 5-mal tägl...,"Aqua purificata, Octyldodecanol, Hydrogenated ...",Warnhinweise\nNur zur äußerlichen Anwendung be...
2,https://www.rossmann.de/de/gesundheit-altaphar...,Lippen-Herpes-Patches,altapharma,NaN,"Das sanfte, runde Polyurethanpflaster ist mit ...",Dank praktischer „Easy-Peel“-Eigenschaften kan...,NaN,Warnhinweise\nKann eine allergische Hautreakti...
3,https://www.rossmann.de/de/gesundheit-altaphar...,Lippen-Herpes-Patches,altapharma,"Artikelpreis 3,99 €","Das sanfte, runde Polyurethanpflaster ist mit ...",Dank praktischer „Easy-Peel“-Eigenschaften kan...,NaN,Warnhinweise\nKann eine allergische Hautreakti...
4,https://www.rossmann.de/de/gesundheit-compeed-...,Herpesbläschen Patch,Compeed,"Artikelpreis 9,99 €",Schützt vor Verschmutzungen und weiteren Infek...,Anwendung des COMPEED® Herpesbläschen-Patch Wa...,Enthält Hydrokolloid zur Förderung der Wundhei...,Warnhinweise\nBei Diabetes vor der Benutzung m...
...,...,...,...,...,...,...,...,...
387,https://www.rossmann.de/de/pflege-und-duft-wel...,UV Glow Fluid LSF 30,Weleda,NaN,für sofortigen Schutz vor UVA/ UVB-Strahlen un...,Sonnenschutzmittel vor dem Sonnen grosszügig a...,"Water (Aqua), Zinc Oxide, Helianthus Annuus (S...",Warnhinweise\nBabys und Kleinkinder vor direkt...
388,https://www.rossmann.de/de/pflege-und-duft-won...,Augenlid-Liftingstripes Gr. M,WONDERSTRIPES,"Artikelpreis 15,99 €",Schönheits-Pflaster zur optischen Augenlidkorr...,So bekommen Sie in wenigen Schritten einen tol...,NaN,NaN
389,https://www.rossmann.de/de/pflege-und-duft-won...,Augenlid-Liftingstripes Gr. M,WONDERSTRIPES,NaN,Schönheits-Pflaster zur optischen Augenlidkorr...,So bekommen Sie in wenigen Schritten einen tol...,NaN,NaN
390,https://www.rossmann.de/de/pflege-und-duft-yea...,Vorteilspack Eye Pad Mask Deep Hydration,YEAUTY,NaN,Spare beim Kauf eines Vorteilspacks gegenüber ...,YEAUTY Augenmasken auf die gereinigte und troc...,"Aqua, Glycerin, Xanthan Gum, Chondrus Crispus ...",NaN
391,https://www.rossmann.de/de/pflege-und-duft-yea...,Vorteilspack Eye Pad Mask Deep Hydration,YEAUTY,"Artikelpreis 8,80 €",Spare beim Kauf eines Vorteilspacks gegenüber ...,YEAUTY Augenmasken auf die gereinigte und troc...,"Aqua, Glycerin, Xanthan Gum, Chondrus Crispus ...",NaN

### Remove all rows without price

In [6]:
df = df[df.price.notna()]
df

,href,name,brand,price,product_details,instruction,ingredients,warnings
0,https://www.rossmann.de/de/pflege-und-duft-niv...,Expert Lift Cellular Multi-Effekt Anti-Age Nac...,NIVEA,"Artikelpreis 19,99 €",Die Cellular Expert Lift Multi-Effekt Anti-Age...,Täglich abends auf das gründlich gereinigte Ge...,"Aqua, Glycerin, Butyrospermum Parkii Butter, R...",NaN
1,https://www.rossmann.de/de/pflege-und-duft-niv...,LUMINOUS630® Skin Glow Liquid Refiner,NIVEA,"Artikelpreis 9,99 €",Der NIVEA LUMINOUS630® Skin Glow Liquid Refine...,Einmal täglich mit einem Wattepad oder der Han...,"Aqua, Glycolic Acid, Glycerin, Sodium Hydroxid...",Warnhinweise\nEs kann ein leichtes Brennen auf...
2,https://www.rossmann.de/de/pflege-und-duft-isa...,Augenpads Hydrogel Hibiskus,ISANA,"Artikelpreis 0,79 €",Wirkung: Die ISANA Hydrogel Augenpads mit Coff...,1. Folie aufreißen und Augenpads herausnehmen....,"Aqua, Propylene Gylcol, Glycerin, Butylene Gly...",NaN
3,https://www.rossmann.de/de/pflege-und-duft-isa...,Korean Skincare Hydration Cream,ISANA,"Artikelpreis 5,99 €",Das Geheimnis strahlender Haut!\nEntdecke die ...,Eine großzügige Menge Creme auf das gereinigte...,"AQUA, DIPROPYLENE GLYCOL, GLYCERIN, NIACINAMID...",NaN
4,https://www.rossmann.de/de/pflege-und-duft-isa...,Hydrogel Augenpads,ISANA,"Artikelpreis 0,79 €",Die ISANA Hydrogel Augenpads mit der Wirkstoff...,1. Folie aufreißen und Augenpads herausnehmen....,"Aqua, Glycerin, Sorbitol, Trehalose, Chondrus ...",Warnhinweise\nMaske zum einmaligen Gebrauch. N...
...,...,...,...,...,...,...,...,...
1335,https://www.rossmann.de/de/pflege-und-duft-isa...,Ultra Sensitiv Barriereschutz-Creme,ISANA MED,"Price 2,99 €",Die ISANA MED SCHUTZ-CREME spendet die ideale ...,ANWENDUNG: Morgens und abends auf die gereinig...,"Aqua, Glycerin, Ethylhexyl Stearate, Helianthu...",NaN
1343,https://www.rossmann.de/de/pflege-und-duft-m-a...,Aqua Intense Barrier Repair Serum,M. Asam,"Price 24,99 €",Schützende Pflege zur gezielten Aufrechterhalt...,"Nach der Reinigung auf Gesicht, Hals und Dekol...","Aqua (Water), Dicaprylyl Carbonate, Squalane, ...",NaN
1345,https://www.rossmann.de/de/pflege-und-duft-m-a...,Magic Care Perfect Eye Augenserum,M. Asam,"Price 24,99 €",Der Bestseller mit optimierter Formel - jetzt ...,Morgens & abends auf die gereinigte Augenparti...,"AQUA (WATER), GLYCERIN, PENTYLENE GLYCOL, SACC...",NaN
1348,https://www.rossmann.de/de/pflege-und-duft-gui...,Eye Serum,Guido Maria Kretschmer,"Price 9,99 €",Entdecke die Gesichtspflege-Linie von Guido Ma...,NaN,"AQUA, GLYCERIN, METHYLPROPANEDIOL, CAFFEINE, P...",NaN
1351,https://www.rossmann.de/de/pflege-und-duft-niv...,Sensitive Gesichtspflege Creme LSF15,NIVEA MEN,"Price 7,99 €",NIVEA MEN Sensitive LSF15 Feuchtigkeitscreme s...,Täglich morgens auf das gereinigte Gesicht und...,"Aqua, Glycerin, C12-15 Alkyl Benzoate, Isoprop...",Warnhinweise\nAugenkontakt vermeiden.

# Remove duplicates that are left

In [7]:
df = df.drop_duplicates()
df

,href,name,brand,price,product_details,instruction,ingredients,warnings
0,https://www.rossmann.de/de/pflege-und-duft-niv...,Expert Lift Cellular Multi-Effekt Anti-Age Nac...,NIVEA,"Artikelpreis 19,99 €",Die Cellular Expert Lift Multi-Effekt Anti-Age...,Täglich abends auf das gründlich gereinigte Ge...,"Aqua, Glycerin, Butyrospermum Parkii Butter, R...",NaN
1,https://www.rossmann.de/de/pflege-und-duft-niv...,LUMINOUS630® Skin Glow Liquid Refiner,NIVEA,"Artikelpreis 9,99 €",Der NIVEA LUMINOUS630® Skin Glow Liquid Refine...,Einmal täglich mit einem Wattepad oder der Han...,"Aqua, Glycolic Acid, Glycerin, Sodium Hydroxid...",Warnhinweise\nEs kann ein leichtes Brennen auf...
2,https://www.rossmann.de/de/pflege-und-duft-isa...,Augenpads Hydrogel Hibiskus,ISANA,"Artikelpreis 0,79 €",Wirkung: Die ISANA Hydrogel Augenpads mit Coff...,1. Folie aufreißen und Augenpads herausnehmen....,"Aqua, Propylene Gylcol, Glycerin, Butylene Gly...",NaN
3,https://www.rossmann.de/de/pflege-und-duft-isa...,Korean Skincare Hydration Cream,ISANA,"Artikelpreis 5,99 €",Das Geheimnis strahlender Haut!\nEntdecke die ...,Eine großzügige Menge Creme auf das gereinigte...,"AQUA, DIPROPYLENE GLYCOL, GLYCERIN, NIACINAMID...",NaN
4,https://www.rossmann.de/de/pflege-und-duft-isa...,Hydrogel Augenpads,ISANA,"Artikelpreis 0,79 €",Die ISANA Hydrogel Augenpads mit der Wirkstoff...,1. Folie aufreißen und Augenpads herausnehmen....,"Aqua, Glycerin, Sorbitol, Trehalose, Chondrus ...",Warnhinweise\nMaske zum einmaligen Gebrauch. N...
...,...,...,...,...,...,...,...,...
1335,https://www.rossmann.de/de/pflege-und-duft-isa...,Ultra Sensitiv Barriereschutz-Creme,ISANA MED,"Price 2,99 €",Die ISANA MED SCHUTZ-CREME spendet die ideale ...,ANWENDUNG: Morgens und abends auf die gereinig...,"Aqua, Glycerin, Ethylhexyl Stearate, Helianthu...",NaN
1343,https://www.rossmann.de/de/pflege-und-duft-m-a...,Aqua Intense Barrier Repair Serum,M. Asam,"Price 24,99 €",Schützende Pflege zur gezielten Aufrechterhalt...,"Nach der Reinigung auf Gesicht, Hals und Dekol...","Aqua (Water), Dicaprylyl Carbonate, Squalane, ...",NaN
1345,https://www.rossmann.de/de/pflege-und-duft-m-a...,Magic Care Perfect Eye Augenserum,M. Asam,"Price 24,99 €",Der Bestseller mit optimierter Formel - jetzt ...,Morgens & abends auf die gereinigte Augenparti...,"AQUA (WATER), GLYCERIN, PENTYLENE GLYCOL, SACC...",NaN
1348,https://www.rossmann.de/de/pflege-und-duft-gui...,Eye Serum,Guido Maria Kretschmer,"Price 9,99 €",Entdecke die Gesichtspflege-Linie von Guido Ma...,NaN,"AQUA, GLYCERIN, METHYLPROPANEDIOL, CAFFEINE, P...",NaN
1351,https://www.rossmann.de/de/pflege-und-duft-niv...,Sensitive Gesichtspflege Creme LSF15,NIVEA MEN,"Price 7,99 €",NIVEA MEN Sensitive LSF15 Feuchtigkeitscreme s...,Täglich morgens auf das gereinigte Gesicht und...,"Aqua, Glycerin, C12-15 Alkyl Benzoate, Isoprop...",Warnhinweise\nAugenkontakt vermeiden.

### There is only one duplicate left -> remove it

In [8]:
href_duplikate_df = df[df.duplicated(subset=["href"], keep=False)].sort_values("href").reset_index(drop=True)

href_duplikate_df

,href,name,brand,price,product_details,instruction,ingredients,warnings
0,https://www.rossmann.de/de/pflege-und-duft-m-a...,Retinol Intense Wrinkle Repair Night Cream,M. Asam,"Artikelpreis 29,99 €",Intensiv pflegende Gesichtscreme mit Retinol f...,Auf das Gesicht auftragen. Nur äußerlich anwen...,"AQUA (WATER), PROPANEDIOL, ISOPROPYL MYRISTATE...",NaN
1,https://www.rossmann.de/de/pflege-und-duft-m-a...,Retinol Intense Wrinkle Repair Night Cream,M. Asam,"Price 29,99 €",Intensiv pflegende Gesichtscreme mit Retinol f...,Auf das Gesicht auftragen. Nur äußerlich anwen...,"AQUA (WATER), PROPANEDIOL, ISOPROPYL MYRISTATE...",NaN

In [9]:
df = df.drop_duplicates(subset=['href'], keep='first')
df.shape

(1119, 8)

In [20]:
df[(df.name.str.contains("Feuchtigkeit")) & (df.brand == "CeraVe") & (df.price.str.contains("14,99"))]['instruction']

168    Die feuchtigkeitsspendende Gesichtscreme von C...
Name: instruction, dtype: object

In [10]:
df.to_csv('products_cleaned.csv', index=False)